[자동차 경주 - 4단계] 리팩토링
next-step/java-racingcar-simple-playground pull request #33
Opened 2024-04-22 11:55 UTC by Starlight258

안녕하세요 진영님 !
자동차 경주 4단계 미션을 완료했습니다 😁

## 궁금한 점
- 도메인 생성시 입력값 검증 책임: `도메인`(Model) vs `Controller` 
   입력값에 대한 검증은 그 전 controller에서 수행하고, 도메인은 검증된 값이 들어왔다고 가정하고 생성하도록 작성했습니다!
   도메인에 검증 로직이 들어가면 검증 로직이 복잡할수록 생성자 코드가 길어지기 때문입니다.
   그리고 입력값이 잘못 들어왔을때 컨트롤러 단에서 사용자에게 빠르게 피드백하여 다시 올바른 값을 입력받기 위해 분리했습니다.
   
   그런데 검증 로직을 해당 도메인에 포함하면 자기 자신에 대한 검증 로직이므로 캡슐화가 더 잘 될 것 같고, 입력값이 아니더라도 잘못된 값에 의해 객체가 생성되는 것을 막을 수 있는 장점이 있을 것 같습니다.
  진영님은 어떤 방법을 더 선호하시는지 궁금합니다 !

- `Controller` 테스트
   Controller 테스트 작성시에 특정 메서드가 잘 호출되었는지를 확인하는 것을 목표로 두었는데 이 방향이 맞는지 궁금합니다! 
   작성하고보니 굳이 이런 테스트가 필요할지 의문이 생겨서 질문 드립니다 !

- 일급 컬렉션 `Cars`
   리팩토링하면서 자동차 경주에 대한 로직이 캡슐화되어 일급 컬렉션 `Cars`로 구현이 되었는데 일급 컬렉션에 맞게 잘 작성되었는지 궁금합니다!

✅ 구현된 코드에 대한 설명은 README.md에서 보실 수 있습니다 ! 
리뷰 부탁드립니다 !! 감사합니다~ 🙇‍♀️

2024-04-22 14:44 UTC, jinyoungchoi95 requested changes
안녕하세요 명지님 😃

몇가지 코멘트남겨두었으니 확인부탁드려요.

감사합니다🙇‍♂️

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/controller/CarRacingController.java
> 입력값에 대한 검증은 controller에서 수행하고, 도메인은 검증된 값이 들어왔다고 가정하고 생성하도록 작성했습니다!
> 도메인에 검증 로직이 들어가면 검증 로직이 복잡할수록 생성자 코드가 길어지기 때문입니다.
> 그리고 입력값이 잘못 들어왔을때 컨트롤러 단에서 사용자에게 빠르게 피드백하여 다시 올바른 값을 입력받기 위해 분리했습니다.
> 
> 그런데 검증 로직을 해당 도메인에 포함하면 자기 자신에 대한 검증 로직이므로 캡슐화가 더 잘 될 것 같습니다.
> 그리고 입력값이 아니더라도 잘못된 값에 의해 객체가 생성되는 것을 막을 수 있는 장점이 있을 것 같습니다.

domain에서 해요. controller에서 fail fast를 해야하는 상황이라면 어쩔 수 없는데, domain에서 검증해야하는 비즈니스로직이라면 controller에 중복이 되더라도 domain에는 무조건 넣습니다.

그래야 안정적으로 생성할 수 있는 domain이 지금 controller가 아니더라도 다른곳에서도 쓰일 수 있어요. 그래서 domain에 필수적으로 넣는거고 fail fast의 상황이 필요하다면 controller에 더 두기도 하는데 개인적으론 fail fast보단 중복코드가 더 불필요하다고 생각해서 domain에만 넣는 편입니다. (fail fast를 해도 io작업이 있지 않는 이상 그렇게 성능차이가 나는것도 아니라서요.)

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/controller/CarRacingController.java
> +public class CarRacingController {
> Controller 테스트 작성시에 특정 메서드가 잘 호출되었는지를 확인하는 것을 목표로 두었는데 이 방향이 맞는지 궁금합니다!
> 작성하고보니 굳이 이런 테스트가 필요할지 의문이 생겨서 질문 드립니다 !

현재 미션에서는 controller에 대한 테스트는 굳이 하지 않으셔도 됩니다. view와 실행 로직을 이어주는 역할로써만 두고 나머지 기능들은 모두 도메인에서 테스트해주시면 되어요.

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/generator/Generator.java
> +public interface Generator {
추상화 잘 해주셨네요. 무슨 Generator인지도 명시해주시면 좋을 것 같아요.

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/test/java/org/duckstudy/model/car/CarTest.java
> +        this.generator = mock(RandomValueGenerator.class);
`Generator`로 추상화를 해주셨으니 `mock`에 대한 의존성을 모두 지우고 추상화를 활용해서 테스트를 작성하는 방법을 고민해주시면 좋을 것 같아요.

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        return List.copyOf(cars);
```suggestion
        return Arrays.stream(carNames)
                .map(name -> new Car(name, generator))
                .toList();
```
로 표현될 수 있어요.

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        this.cars = createCars(carNames, generator);
생성자는 보통 안정적인 객체를 보장하는 주생성자 밑에 여러 부생성자를 두는것이 좋아요. 현재는 15~17의 생성자가 된다면,
```suggestion
        this(createCars(carNames, generator));
```
가 될 수 있겠네요.

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +            outputView.printMessage(getPositions());
`View`에 대한 의존성은 domain 에서 모두 제거해주세요.

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +                .orElse(INITIAL_POSITION);
1. 메소드로 빼면 어떨까요?
2. max를 계산하지 못하는 상황이라면 0을 내보내는 것이 아닌 예외를 발생시켜야하지 않을까요?

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +                .filter(car -> car.getPosition() == maxPosition)
getter를 사용해서 로직을 호출하는 것은 객체끼리의 메시지를 내보내는 형태는 아니에요.

`Car`에 maxPosition인지에 대해서 메시지를 내보내는 형태로 바꾸어보면 어떨까요?

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        return new Cars(winners);
```suggestion
        List<Car> winners = cars.stream()
                .filter(car -> car.getPosition() == maxPosition)
                .toList();
        return new Cars(winners);
```
여도 되지 않을까요? `ArrayList`는 추상화된 `List`와 다른 구현체에요. `추상화에 의존해야지, 구체화에 의존하면 안된다`라는 말이 왜 나왔을까요?

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +    }
`,`를 구분자로 출력하는 것은 화면의 요구사항이에요. name을 내보내도록하고 `,`처리는 view에서 해주세요.

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +    }
위와 마찬가지입니다.

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/controller/Validator.java
> +public class Validator {
`Validator`는 단순히 vaildation처리만 해서 exception을 내보내도록하고 `OutPutView`는 굳이 메시지에 대한 처리를 하지 않아도 되지 않을까요?
- Validator : 값에 대한 예외처리
- OutputView : 화면에 대한 출력처리

2024-04-22 14:44 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/controller/Validator.java
> +        if (repetitionNum <= 0) {
0은 상수로 표현될 수 있겠네요.

2024-04-23 05:43 UTC, Starlight258 commented on src/main/java/org/duckstudy/controller/CarRacingController.java
그렇군요 !! 검증 로직은 도메인에 두는게 더 낫겠네요! 맞춰서 수정해보겠습니다 !!

2024-04-23 08:21 UTC, Starlight258 commented on src/main/java/org/duckstudy/controller/CarRacingController.java
> +public class CarRacingController {
그렇군요 !! 알겠습니다 !

2024-04-23 08:33 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/generator/Generator.java
> +public interface Generator {
이름이 너무 추상적이긴 하네요! 
`RandomValueGenerator`로 인터페이스 이름을 수정하고 구현체는 `DefaultRandomValueGenerator`로 수정하겠습니다 ~!

2024-04-23 08:45 UTC, Starlight258 commented on src/test/java/org/duckstudy/model/car/CarTest.java
> +        this.generator = mock(RandomValueGenerator.class);
넵..! mock은 최소화로 사용하는게 좋을 것 같아요. 다시 테스트 작성하겠습니다 !!

2024-04-23 10:49 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        return List.copyOf(cars);
stream을 이용하면 더 간단하네요 !

2024-04-23 11:05 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        this.cars = createCars(carNames, generator);
그렇군요 ! createCars가 멤버 메서드여서 this 전에 호출이 불가능하니 this 안에 createCars 메서드 내용을 넣어서 수정하겠습니다 !!
```java
public Cars(String[] carNames, RandomValueGenerator randomValueGenerator, OutputView outputView) {
      this(Arrays.stream(carNames)
              .map(carName -> new Car(carName, randomValueGenerator, outputView))
              .collect(Collectors.toList()));
  }
```

2024-04-23 11:09 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +            outputView.printMessage(getPositions());
관심사의 분리를 지켜서 코드 수정하겠습니다 ..!

2024-04-23 11:57 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +                .orElse(INITIAL_POSITION);
메서드로 빼고 max를 구하지 못할 경우에는 예외 발생시키도록 하겠습니다 !

2024-04-23 12:12 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +                .filter(car -> car.getPosition() == maxPosition)
그 방법이 더 객체지향에 적합하네요 !!  getter로 객체의 데이터를 직접 요청하지말고 객체에게 직접 판단하도록 수정하겠습니다 !

2024-04-23 12:18 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        return new Cars(winners);
앗 맞습니다,, 구체 클래스에 의존하면 코드 변경 가능성이 높아집니다,, 수정하겠습니다 ! 😭

2024-04-23 13:17 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +    }
도메인에 view 로직이 포함되어 있었네요,, 수정하겠습니다 !

2024-04-23 13:17 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +    }
넵 데이터만 반환하도록 수정하겠습니다~!

2024-04-23 13:18 UTC, Starlight258 commented on src/main/java/org/duckstudy/controller/Validator.java
> +public class Validator {
예외 메세지도 OutputView에서 관리하는게 낫지 않을까라고 생각했는데, 검증 예외 메세지는 검증 코드에 포함시키는게 오히려 응집도를 높일 것 같네요 !!

2024-04-23 13:19 UTC, Starlight258 commented on src/main/java/org/duckstudy/controller/Validator.java
> +        if (repetitionNum <= 0) {
앗 ,, 숫자가 포함되어있었네요 수정하겠습니다 !!

2024-04-23 13:21 UTC, Starlight258 commented
@jinyoungchoi95
리뷰해주신 사항들 덕분에 많이 배웠습니다 🙇‍♀️
감사합니다 ! 😁

2024-04-23 13:22 UTC, Starlight258 commented
@jinyoungchoi95
리뷰해주신 사항들 덕분에 많이 배웠습니다 🙇‍♀️
감사합니다 ! 😁

2024-04-23 15:28 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +    }
`repetitionNum`은 Car의 특성이 아니지만 Cars에 게임 로직을 모아두어서 repetitionNum 검증 코드를 포함시켰습니다. 
Cars에 포함하는게 좋을지, 아니면 다른 곳으로 이동하는게 좋을지 의견 여쭤봐도 될까요 ??

2024-04-28 14:32 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +    }
일급컬랙션 `Cars`의 관심사는 `Car`이라는 컬랙션에 대한 관심이기 때문에 단순히 반복횟수에 대한 validation은 어색한 것 같아요. 별도의 value object와 같은 클래스로 분리하는게 좋을 것 같네요.

2024-04-28 14:42 UTC, jinyoungchoi95 requested changes
안녕하세요 명지님 😃

몇가지 코멘트남겨두었으니 확인부탁드려요.

감사합니다🙇‍♂️

2024-04-28 14:42 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        this.cars = List.copyOf(cars);
`copyOf`는 어디까지 복사해서 넣어주나요? 복사를 할 때 어느정도로 복사하는것이 적절할까요?

https://ksh-coding.tistory.com/77

2024-04-28 14:42 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/controller/CarRacingController.java
> +            outputView.printIntermediateResult(cars.getAllNames(), cars.getAllPositions());
이렇게 들어오면 List의 index를 각각 따로 사용할 수도 있으니 `Cars`는 `List<Car>`만 내보내도록하고 `List<Car>`를 돌면서 필요한 값을 받아 출력하는것이 낫지 않을까요?

2024-04-28 14:42 UTC, jinyoungchoi95 commented on src/test/java/org/duckstudy/model/car/CarsTest.java
> +        RandomValueGenerator randomValueGenerator = appConfig.randomValueGenerator();
`Random`구현체를 가져오는 것보다는 `CarTest`처럼 커스텀된 구현체를 넣는게 더 적절하지 않을까요?

2024-04-28 14:42 UTC, jinyoungchoi95 commented on src/test/java/org/duckstudy/model/car/CarsTest.java
> +            assertThat(winners.getAllNames()).isSubsetOf(CAR_NAMES);
이러면 winner를 계산할 때 예를들어 position이 1, 0, 1인 경우를 테스트하진 못하는데요. `Cars`를 생성할 때 원하는 위치를 가지는 `List<Car>`들을 주입한다면 `moveAll`도 하지 않고 `calculateWinners`를 테스트할 수 있지 않을까요?

2024-04-28 14:42 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/generator/RandomValueGenerator.java
> +public interface RandomValueGenerator {
숫자를 반환하기 때문에 `NumberGenerator`까지가 적절하지 않을까 싶어요. 현재 이 인터페이스는 "숫자를 만드는 행위"를 추상화한 것이니까요.

2024-04-28 14:42 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/generator/DefaultRandomValueGenerator.java
> +public class DefaultRandomValueGenerator implements RandomValueGenerator {
위에 이어나가면 오히려 여기선 `RandomValueGenerator`가 더 적절하겠네요.

2024-04-28 14:42 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/config/AppConfig.java
> +public class AppConfig {
`Config`는 현재 미션상에선 과한 스펙이기 때문에 그냥 Application에서 생성하여쓰셔도됩니다.

2024-04-29 05:16 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +    }
맞습니다 !! 값 객체로 분리하는 방법이 있었네요 ! 감사합니다~

2024-04-30 11:13 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        this.cars = List.copyOf(cars);
copyOf는 새로운 리스트를 만들어 객체들을 복사하고, unmodifiableList는 원본 리스트의 참조를 반환하지만 read-only로 반환합니다. copyOf를 사용한 이유는 원본 리스트가 변경될 경우 getter로 얻은 복사본 리스트가 함께 변경될 수 있기 때문에, 참조를 끊어주기 위해 사용했습니다.

하지만 원본 리스트가 변경될 경우 복사한 리스트와 상태가 달라지므로 데이터 정합성 측면에서 문제가 발생할 것 같아요. 
그리고 수정을 막는것이 목적이므로 굳이 copyOf로 불필요한 복사를 하는 것보다 unmodifiableList로 원본 리스트 참조는 유지하되 read-only로 반환하는게 좋을 것 같아요.

만약 Cars 외부에서 생성자로 반환한 복사한 리스트의 내부 객체 요소(Car)을 변경하는 작업이 수행될 경우, deep copy가 아니므로 원본 리스트의 객체도 영향이 가서 위험하지 않을까 라는 생각도 했는데요,,,... 
하지만 일급 컬렉션의 특성상 리스트의 내부 객체 요소 변경 작업은 컬렉션 안에서만 이루어져 외부에서 변경되지 않음을 전제조건으로 하기 때문에 괜찮을 것 같습니다 !

2024-04-30 12:15 UTC, Starlight258 commented on src/main/java/org/duckstudy/controller/CarRacingController.java
> +            outputView.printIntermediateResult(cars.getAllNames(), cars.getAllPositions());
아 그렇겠네요! 리스트만 인자로 주면 출력시 인덱스 에러가 날 확률이 적고 더 명확할 것 같습니다 !!

2024-04-30 12:31 UTC, Starlight258 commented on src/test/java/org/duckstudy/model/car/CarsTest.java
> +        RandomValueGenerator randomValueGenerator = appConfig.randomValueGenerator();
테스트를 `AppConfig`로부터 의존성을 불러와서 실행시키면 현재 운영 환경에서 로직이 잘 돌아가는지 테스트할 수 있어서 그렇게 작성했습니다 ! 
그런데 생각해보면 테스트 환경이 `AppConfig` 설정에 의존하게 되어 테스트의 독립성이 깨지겠네요 ! 🧐

테스트에서 환경 설정은 분리하고 테스트 대상 클래스의 동작을 검증하는데에만 집중하도록 하겠습니다 !
감사합니다 !!

2024-04-30 12:37 UTC, Starlight258 commented on src/test/java/org/duckstudy/model/car/CarsTest.java
> +            assertThat(winners.getAllNames()).isSubsetOf(CAR_NAMES);
아 맞습니다 !! 위치를 설정하면 우승자가 예상대로 계산되는지 검증할 수 있겠네요 ! 수정하겠습니다 !

2024-04-30 13:10 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/generator/RandomValueGenerator.java
> +public interface RandomValueGenerator {
인터페이스 이름을 어떻게 작성해야할지 고민되었는데 반환값 기준으로 작성하는 좋은 방법이 있었네요 !

2024-04-30 13:19 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/generator/DefaultRandomValueGenerator.java
> +public class DefaultRandomValueGenerator implements RandomValueGenerator {
피드백 감사합니다 ! 구현체에서는 랜덤값을 생성한다는 의미가 드러나는게 필요하네요 !!
그런데 현재 구현에서는 숫자값만 반환하므로 제안해주신 인터페이스 이름인 `NumberGenerator`에 맞춰
`RandomNumberGenerator`가 더 명확한 것 같은데 어떻게 생각하시나요?

2024-04-30 13:23 UTC, Starlight258 commented on src/main/java/org/duckstudy/config/AppConfig.java
> +public class AppConfig {
앗 그렇군요 ! 현재 미션에서는 굳이 Config 클래스까지 만들 필요가 없었던 거네요 !
지적 감사합니다~ 상황에 맞게 적절하게 설계해보겠습니다 !

2024-05-01 06:40 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        this.cars = List.copyOf(cars);
외부에서 리스트참조값에 대한 정보를 알고있어이를 끊을수있는건 맞지만 방어적복사의 관점에서 Car 각각에대한 접근이 가능하기때문에 위험할수도 있어요. 이들을 방어적복사로 일일히 모두 복사하기 힘들기때문에 최대한 객체를 불변하게 만들어 객체접근으로 상태를 변경하지못하게 하려는 이유도 있고요 (물론 언어에서 기능을 제공하는 언어도 있습니다)

방어적복사를 구현하실필요는없으나 깊은복사라고해도 결국 참조값접근은 가능하다는점만 알아두시면 좋을거같아요.

2024-05-01 06:50 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/generator/DefaultRandomValueGenerator.java
> +public class DefaultRandomValueGenerator implements RandomValueGenerator {
네 좋은거같아요.

2024-05-01 07:33 UTC, jinyoungchoi95 approved these changes
안녕하세요 명지님 😃

현재 미션에서 해야할 학습과 구현을 충분히 하신 것 같아 머지하겠습니다.

감사합니다🙇‍♂️

2024-05-01 07:33 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/car/Car.java
> +        if (randomValue >= MIN_MOVEMENT_VALUE) {
움직임 자체에 대한 책임을 넘겨서 `MovableStratey`로 두고 4이상이면 true을 반환하는 구현체를 두는 설계도 생각해볼수있습니다.

2024-05-01 07:33 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/generator/RandomNumberGenerator.java
> +        return new Random().nextInt(EXCLUSIVE_MAX_VALUE);
계속 `Random`을 생성하는거보다 상수로 두면 불필요한 객체생성을 막을수 있겠네요.

2024-05-01 07:33 UTC, jinyoungchoi95 commented on src/test/java/org/duckstudy/model/car/CarsTest.java
> +        cars.moveAll();
position을 1,0,1로 각각 생성한 객체를 두면 moveAll도 안할수있겠네요.

2024-05-01 07:33 UTC, jinyoungchoi95 commented on src/test/java/org/duckstudy/model/car/CarsTest.java
> +        assertThat(winners.toList().size()).isEqualTo(2);
hasSize를 사용하고, 전체 assertion은 asserAll로 묶는게 좋을거같아요.

2024-05-01 07:45 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Cars.java
> +        this.cars = List.copyOf(cars);
그렇군요! 내부 객체의 불변성이 보장되지 않는다면 깊은 복사를 해서 내부 요소들의 참조가 끊기더라도 여전히 객체가 변경이 가능한 문제가 있네요 !!
Car은 움직일때마다 위치 특성이 달라지므로 불변 객체로 생성한다면 이동시마다 새로운 객체를 반환해야하는데 오히려 그 방법이 안전성이 높고 실수할 가능성이 낮아질 것 같아요.
감사합니다 ~!!

2024-05-01 08:04 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/car/Car.java
> +        if (randomValue >= MIN_MOVEMENT_VALUE) {
전략 패턴을 사용하면 차가 움직이는 방식을 변경할 수 있겠군요 !!

2024-05-01 08:58 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/generator/RandomNumberGenerator.java
> +        return new Random().nextInt(EXCLUSIVE_MAX_VALUE);
앗 그러네요! 요청마다 Random 객체가 생성되는 것보다 한번 생성하고 공유하는 것이 좋겠네요! 감사합니다 !

2024-05-01 09:05 UTC, Starlight258 commented on src/test/java/org/duckstudy/model/car/CarsTest.java
> +        cars.moveAll();
이전에는 position을 Car 객체 안에서만 관리해서  position을 생성자에서 지정할 수 없어서 moveAll을 호출했습니다 ㅜㅜ
하지만 Car을 불변 객체로 변경한 후 position을 외부에서 지정할 수 있어서 moveAll()을 호출하지 않고도 테스트할 수 있겠네요!
반영하겠습니다 !

2024-05-01 09:08 UTC, Starlight258 commented on src/test/java/org/duckstudy/model/car/CarsTest.java
> +        assertThat(winners.toList().size()).isEqualTo(2);
검증 문장이 여러개 있을 경우 assertAll을 꼭 이용하겠습니다 ! 감사합니다~~

2024-05-01 09:09 UTC, Starlight258 commented
@jinyoungchoi95
피드백 감사합니다 ! 😁
많이 배우네요 ㅠㅠ 감사해요 !!

2024-05-02 14:06 UTC, merged