자동차 경주 게임
next-step/java-racingcar-simple-playground pull request #7
Opened 2024-04-07 13:20 UTC by PlusUltraCode

예시본

2024-04-09 05:59 UTC, kokodak requested changes
안녕하세요 동호님! 미션 고생하셨어요.

객체 분리를 통해 책임과 역할을 적절히 나누려고 노력하신 점이 정말 좋았어요.

전반적으로 수정이 필요해보이는 곳들에 대해 코멘트를 남겼습니다. 많이 고민해보시고, 동호님의 생각을 정리해서 답변으로 남겨주세요!

추가로, 코드 컨벤션이 망가져있는 부분들이 좀 있었어요. 앞으로는 인텔리제이 자동정렬 기능을 활용하셔서 일관되는 스타일을 유지해주시면 좋을 것 같아요 ! 😁

2024-04-09 05:59 UTC, kokodak commented on src/main/java/controller/Application.java
> +        final var carNames = Input.getNames();
var 자료형의 장단점은 무엇이 있을까요?

또한 전반적으로 var 사용에 대한 통일성이 부족한 것 같아요. 코드 컨벤션을 한 방향으로 맞추는 것을 추천드립니다!

ex) var를 사용한다 or 사용하지 않는다

2024-04-09 05:59 UTC, kokodak commented on src/main/java/controller/RaceGame.java
> +    private static List<Car> winningCars = new ArrayList<>();
```suggestion
    private Cars carRepository;

    private List<Car> winningCars = new ArrayList<>();
```
위의 코드와는 무엇이 다른지 설명해주세요!

또한, 만약 서로 다른 RaceGame이 두개 이상 필요하다면 어떻게 될까요?

2024-04-09 05:59 UTC, kokodak commented on src/main/java/controller/RaceGame.java
> +    public  RaceGame(String[] names , int gameCount){
```suggestion
    public RaceGame(String[] names, int gameCount) {
```
사소하지만, 공백에 대한 컨벤션도 잘 지켜주세요!

2024-04-09 05:59 UTC, kokodak commented on src/main/java/controller/RaceGame.java
> +    }
이 코드 블럭은 `RaceGame`의 생성자 블럭인데요!

생성자는 말 그대로 객체의 생성을 책임지는 곳이라고 생각해요.

지금은 객체의 생성과는 상관없는 많은 로직들이 들어가 있는 것으로 보이는데, 동호님은 어떻게 생각하시나요?

2024-04-09 05:59 UTC, kokodak commented on src/main/java/objects/Car.java
> +            carPosition += "-";
String에서의 덧셈 연산은 리소스 관점에서 상당히 비효율적일 수 있어요.

`StringBuilder` or `StringBuffer` 를 키워드로 검색해보시고, String에서의 덧셈 연산이 왜 비효율적인지 저에게 알려주세요!

2024-04-09 05:59 UTC, kokodak commented on src/main/java/objects/Car.java
> +    }
Car 도메인이 Random 이라는 `개발자가 제어할 수 없는 값`에 의존하기 시작하면서, `move()` 메서드에 대한 단위 테스트가 어려워졌을거에요.

어떻게 해야 `move()` 메서드를 테스트하기 쉬운 코드로 바꿀 수 있을까요?

다시 말하면, 어떻게 해야 Random 으로부터 의존성을 벗어날 수 있을까요?

태연님과 제가 작성한 코드를 참고하셔서, 한번 리팩터링 진행해보세요. 관련 클래스 이름은 `NumberGenerateStrategy` 입니다!

2024-04-09 05:59 UTC, kokodak commented on src/main/java/objects/Car.java
> +    }
is~ 라는 메서드명은 보통 boolean을 반환하는 것이 관례적이에요.

메서드명에서 유추하건데, 해당 메서드의 역할과 책임은 `그것이 같은 위치인가?` 에 대한 물음에 답하는 것으로 보이는데요!

`winningCars.add()` 를 호출하는 것은 해당 메서드의 책임과는 알맞지 않는 코드 맥락인 것 같아요. 메서드명을 수정하거나, 메서드를 적절히 분리하는 방향을 추천드릴게요 !

2024-04-09 05:59 UTC, kokodak commented on src/main/java/objects/Cars.java
> +
불필요한 개행은 모두 제거해주세요!

여기뿐만 아니라, 전체적으로 신경써서 제거해주세요~!

2024-04-09 05:59 UTC, kokodak commented on src/main/java/objects/Cars.java
> +            System.out.println(myCar.getName() + " : " + carPosition);
콘솔에 화면을 찍어내는 객체를 Output 객체로 책임 분리를 하셨지만, Cars 라는 도메인 객체가 여전히 출력에 관한 역할을 담당하고 있네요!

이는 올바른 책임 분리가 일어났다고 보기 힘들 것 같아요. 출력은 Output 객체에, 입력은 Input 객체에 확실하게 책임을 나누어주시면 좋을 것 같아요!

2024-04-09 05:59 UTC, kokodak commented on src/main/java/view/Input.java
> +        }
재시도 로직을 잘 구현해주셨군요! 👍

2024-04-09 05:59 UTC, kokodak commented on src/main/java/view/Input.java
> +            if(name.length()>=5)return false;
`자동차 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다.`

5글자까지는 가능해야하지 않을까요? 🤔

2024-04-09 05:59 UTC, kokodak commented on src/main/java/view/Input.java
> +            if(name.length()>=5)return false;
```suggestion
            if (name.length() >= 5) {
                return false;
            }
```
코드 컨벤션을 신경 써주세요. 앞으로 동호님이 작성하실 코드는 동호님 혼자서만 보는 코드가 아닙니다!

협업하는 동료를 위해서라도, `반드시` 컨벤션은 맞춰서 제출해주세요 ㅎㅎ

모두 신경쓰기 어렵다면, 인텔리제이 자동정렬을 적극 활용해주시면 좋아요 !

2024-04-09 05:59 UTC, kokodak commented on src/test/java/objects/CarTest.java
> +    }
테스트 코드를 조금 더 신경써서 보강해주세요.

아직은 처음이라 어색하고 어려울 수 있지만, 저와 태연님이 작성한 코드에 포함되어있는 테스트 코드들을 참고해서 작성해보시면 좋아요!

어색하고 어렵다는 이유로 공부를 미루게 되면 앞으로도 영원히 작성할 수 없어요. 동호님의 근성과 열정을 저에게 보여주세요 ㅎㅎ

2024-04-09 05:59 UTC, kokodak commented on src/main/java/objects/Cars.java
> +            System.out.println(myCar.getName() + " : " + carPosition);
`MVC 패턴` 이라는 키워드로 추가 학습을 해보시는 것을 권장드립니다 😁

2024-04-09 05:59 UTC, kokodak commented on src/main/java/objects/Car.java
> +    }
setter 메서드를 만드는 것은 지양해주세요.

외부에서 필드 값을 함부러 수정하는 것을 막기 위해서, 필드의 접근 제어자를 private으로 감춰놓으신 것 같아요.

하지만 setter 메서드가 존재하는 한, private 접근 제어자의 의미가 많이 퇴색될 것 같아요!

2024-04-30 08:36 UTC, PlusUltraCode commented on src/main/java/controller/Application.java
> +        final var carNames = Input.getNames();
아직 var형을 쓰는게 익숙지 않아 사용하지 않는 방향으로 바꿔보겠습니다.

2024-04-30 08:56 UTC, PlusUltraCode commented on src/main/java/controller/RaceGame.java
> +    private static List<Car> winningCars = new ArrayList<>();
java의 클래스는 한 번만 메모리로 로드됩니다.
static으로 선언하게 되면 static 영역에 저장되어 클래스가 끝날 때 까지 계속 존재하게 됩니다. 
static이 아닌 변수를 new 로 객체를 생성하게 되면 heap영역에 저장되어 가비지 컬렉터에 의해 자동으로 관리되어 집니다.
이러한 특징으로 객채를 생성하지 않고 여러 객체가 해당 변수나 함수에 접근이 가능해집니다. 
ex) Math.random() 
 
 
 두 번째 질문 만약 서로 다른 RaceGame이 두개 이상 필요하다면 어떻게 될까요?
답변 : 고민해본 결과 서로 다른 RaceGame일 경우에는 static을 선언 하는쪽이 메모리 사용에 효과적일거라 생각합니다.  여러개의 RaceGame객채를 생성하게 되면 static으로 선언하지 않은 모든 변수들 또한 메모리에 상주하게 됩니다.
이러면 메모리 공간적으로 많이 비효율적이라 생각합니다.

2024-04-30 08:58 UTC, PlusUltraCode commented on src/main/java/controller/RaceGame.java
> +    public  RaceGame(String[] names , int gameCount){
넵!! 수정했습니다

2024-04-30 09:03 UTC, PlusUltraCode commented on src/main/java/controller/RaceGame.java
> +    }
만들 때는 의식을 못했는데 다시 보니 객채를 생성하고 그에 더해서 게임을 진행하고 게임 승자까지 만드는 코드들을 써놨네요. 개별적으로 분리해서 작성했어야 되는데 의식하고 코드를 작성하겠습니다!!

2024-04-30 09:26 UTC, PlusUltraCode commented on src/main/java/objects/Car.java
> +            carPosition += "-";
String 은 한번 생성하게 되면 불변특성 때문에 문자열을 더하거나 수정할 때마다 새로운 String 객체를 생성한다고 합니다. 이러한 작업은 메모리에 많은 부담을 줄 수 있습니다.
해결책은 StringBuilder 와 StringBuffer가 있다고 합니다.
StringBuilder은 스레드의 병행성 구현을 하지않아 단인 스레드 환경만 사용해야 합니다.
StringBuffer는 멀티스레딩 환경에서도 구현 가능합니다.
따라서 개발환경에서 단일스레드인 경우에는 StringBuilder가 속도측면에서 이득이라고 해서 
StringBuilder을 사용하여 수정하겠습니다.

2024-04-30 09:27 UTC, PlusUltraCode commented on src/main/java/view/Input.java
> +        }
감사합니다. ^,^

2024-04-30 09:28 UTC, PlusUltraCode commented on src/main/java/view/Input.java
> +            if(name.length()>=5)return false;
수정하였습니다. 감사합니다

2024-04-30 09:36 UTC, PlusUltraCode commented on src/main/java/view/Input.java
> +            if(name.length()>=5)return false;
의식적인 습관 드리겠습니다!!

2024-05-11 03:22 UTC, merged